kind: Service
apiVersion: v1
metadata:
  name: @containername@
  labels:
    app: @containername@
spec:
  selector:
    app: @containername@
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8044
  type: NodePort
  #type: LoadBalancer
  #ports:
  #- port: 8080
  #selector:
  #  app: @containername@
  
