kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.containername }}
  labels:
    app: {{ .Values.containername }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.containerport }}
  selector:
    app: {{ .Values.containername }}
  
